version: '3'
services:
  redis6379:
    image: redis:4
    container_name: redis_6379
    restart: unless-stopped
    ports:
      - "6379:6379"
    expose:
      - "6379"
    environment:
      appendonly: "yes"
    volumes:
      - /data/docker/redis/6379:/data
  redis6380:
    image: redis:4
    container_name: redis_6380
    restart: unless-stopped
    ports:
      - "6380:6379"
    expose:
      - "6380"
    environment:
      appendonly: "yes"
    volumes:
      - /data/docker/redis/6380:/data
  redis6381:
    image: redis:4
    container_name: redis_6381
    restart: unless-stopped
    ports:
      - "6381:6379"
    expose:
      - "6381"
    environment:
      appendonly: "yes"
    volumes:
      - /data/docker/redis/6381:/data
  redis6382:
    image: redis:4
    container_name: redis_6382
    restart: unless-stopped
    ports:
      - "6382:6379"
    expose:
      - "6382"
    environment:
      appendonly: "yes"
    volumes:
      - /data/docker/redis/6382:/data
  redis6383:
    image: redis:4
    container_name: redis_6383
    restart: unless-stopped
    ports:
      - "6383:6379"
    expose:
      - "6383"
    environment:
      appendonly: "yes"
    volumes:
      - /data/docker/redis/6383:/data
  redis6384:
    image: redis:4
    container_name: redis_6384
    restart: unless-stopped
    ports:
      - "6384:6379"
    expose:
      - "6384"
    environment:
      appendonly: "yes"
    volumes:
      - /data/docker/redis/6384:/data