apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-rs-demo
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mynginx
      release: canary
  template:
    metadata:
      name: myapp-pod
      namespace: default
      labels:
        app: mynginx
        release: canary
        environment: qa
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
              name: http
