version: '3'
services:
  rabbitmq-1:
    image: rabbitmq
    hostname: rabbitmq-1
    ports:
      - "5672:5672"
      - "15672:15672"

  rabbitmq-2:
    image: rabbitmq
    hostname: rabbitmq-2
    links:
      - rabbitmq-1
    environment:
      - CLUSTERED=true
      - CLUSTER_WITH=rabbitmq-1
      - RAM_NODE=true
    ports:
      - "5673:5672"
      - "15673:15672"

  rabbitmq-3:
    image: rabbitmq
    hostname: rabbitmq-3
    links:
      - rabbitmq-1
      - rabbitmq-2
    environment:
      - CLUSTERED=true
      - CLUSTER_WITH=rabbitmq-1
    ports:
      - "5674:5672"