apiVersion: v1
kind: Service
metadata:
  name: service-redis
  namespace: default
spec:
  selector:
    app: redis
    role: logstore
  clusterIP: 10.99.99.99
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: service-nginx
  namespace: default
spec:
  selector:
    app: mynginx
    release: canary
  clusterIP: 10.98.98.98
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 80