version: "3.1"
services:
  cassandra-1:
    image: cassandra:3.11
    restart: unless-stopped
    container_name: cassandra-1
    environment:
          - CASSANDRA_BROADCAST_ADDRESS=cassandra-1
    ports:
      - "7000:7000"
      - "7001:7001"
      - "7199:7199"
      - "9042:9042"
      - "9160:9160"
    volumes:
      - "/opt/docker/cassandra-1:/var/lib/cassandra"
#  cassandra-2:
#    image: cassandra:3.11
#    restart: unless-stopped
#    container_name: cassandra-2
#    environment:
#          - CASSANDRA_BROADCAST_ADDRESS=cassandra-2
#    ports:
#      - "7000:7000"
#      - "7001:7001"
#      - "7199:7199"
#      - "9042:9042"
#      - "9160:9160"
#    volumes:
#      - "/opt/docker/cassandra-1:/var/lib/cassandra"
#  cassandra-3:
#    image: cassandra:3.11
#    restart: unless-stopped
#    container_name: cassandra-3
#    environment:
#          - CASSANDRA_BROADCAST_ADDRESS=cassandra-3
#    ports:
#      - "7000:7000"
#      - "7001:7001"
#      - "7199:7199"
#      - "9042:9042"
#      - "9160:9160"
#    volumes:
#      - "/opt/docker/cassandra-1:/var/lib/cassandra"