version: "3"
services:
  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
    networks:
      - sonarnet
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
#    volumes:
#      - D:\DockerVolumes\sonarqube_conf:/opt/sonarqube/conf
#      - D:\DockerVolumes\sonarqube_data:/opt/sonarqube/data
#      - D:\DockerVolumes\sonarqube_extensions:/opt/sonarqube/extensions
#      - D:\DockerVolumes\sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    links:
      - db
  db:
    image: postgres
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
#    volumes:
#      - D:\DockerVolumes\postgresql:/var/lib/postgresql
    # This needs explicit mapping due to https://github.com/docker-library/postgres/blob/4e48e3228a30763913ece952c611e5e9b95c8759/Dockerfile.template#L52
#      - D:\DockerVolumes\postgresql_data:/var/lib/postgresql/data
networks:
  sonarnet:
    driver: bridge
#volumes:
#  - sonarqube_conf:
#  - sonarqube_data:
#  - sonarqube_extensions:
#  - sonarqube_bundled-plugins:
#  - postgresql:
#  - postgresql_data: