version: '3.1'

services:

  db:
    image: mysql
#    command: --default-authentication-plugin=mysql_native_password
#    restart: unless-stopped
    container_name: mysql8
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    expose:
      - "3308"
    volumes:
#      - "/opt/docker/mysql/version8:/var/lib/mysql"
      - "/Users/spontaneously/Applications/docker/mysql:/var/lib/mysql"